buzzfeed/solid

- CONTRIBUTING.md
- DEVELOPING.md
- Gruntfile.js
- Makefile
This branch:
* Updates `CONTRIBUTING.md` with an updated workflow and deploy instructions
* Simplifies `DEVELOPING.md`
* Fixes a grunt bug that caused releases to not include distribution binaries
> Release docs for rig deploys

- docs/forms.html
Our current documentation for form fieldset--error mistakenly says to add the fieldset--warning class where should say --error. Fixed so the docs are consistent with how this works.
> Fix documentation for inline error / warning messaging

- _lib/solid-utilities/_typography.scss
removed importants from list-unstyled class's margin and padding
> SOLID-358: remove importants from list-unstyled margin and padding

- docs/mixins.html
- add `&` and remove `.` from targeted selector.
> SOLID-399 Fix error in docs for generate breakpoint prefix mixin

- docs/svg-icons.html
-Add half space of padding between icon and text in accessibility example for svg icons docs
> SOLID-398 Tweak icon docs

- _lib/solid-utilities/_buttons.scss
Removed outline override for button focus and just left it on :active
Tab through the Buttons page in the Solid docs to see the change. Unfortunately this DOES show up on click because technically you are still focused while you're clicking. I think this is the best solution for now. We can alert designers and solicit feedback from them, but I think the benefits outweigh the negatives here.
> SOLID-367 Remove Override For Button Focus Outline

- _lib/solid-utilities/_forms.scss
-Fixes bug with scroll bar jumping during toggle in Google Chrome (See bug ticket for additional details on how to reproduce)
> SOLD-386: Toggling Checkboxes/Radios Within List Causes Parent to Scroll in Google Chrome

- _lib/solid-base/_typography.scss
- docs/colors.html
- Added text-gray to `body`, so we now have default body copy for reals.
- Fixed Colors docs to use the `text-gray` class where it says it's being used.
> SOLID-407: Add Text-Gray To Body Copy

- docs/_posts/release-notes/2017-01-20-2.6.0.html
- npm-shrinkwrap.json
- package.json
Added: Teal and purple fill and SVG fill colors
Added: Purple text color
Added: Apple News and RSS social buttons
Added: Body copy is now .text-gray as default
> Release 2.6.0

- _lib/solid-base/_typography.scss
- _lib/solid-utilities/_typography.scss
Adds support for hover states in default links, link-blue, link-gray, and link-gray-lighter by transitioning svg fill colors
> SOLID-404: SVG hover states

- _lib/solid-base/_base.scss
Currently, the homepage suffers a Flash of Invisible Text (FOIT) when the fonts are loaded.
I found the culprit `font: inherit`. 
Because we have [that system](https://github.com/bramstein/fontfaceobserver) to lazy load fonts where we set `font-family` in `body` and then update when `.fonts-loaded` is added, it seems that `font: inherit` breaks that expectation since `body` is in charge of that.
> SOLID-418: solid: fix flash of invisible text

- _lib/solid-base/_typography.scss
- docs/_posts/release-notes/2017-03-10-2.6.1.html
- Reduces reach of svg hover styles to target svgs appearing within explicitly called .link-blue, .link-gray, .link-gray-lighter, and .link-white classes only. 
- Additionally fixes two bugs on previous release notes - closes an a tag and fixes unexpected formatting due to parentheses.
> SOLID-419 Fix SVG hover and release bugs

- _lib/solid-utilities/_flexbox.scss
- docs/_posts/release-notes/2017-03-10-2.6.1.html
- docs/flexbox.html
- docs/release-notes.md
Added styles for
```
justify-content: space-between
justify-content: space-between
align-items: space-between
align-items: space-between
```
This was originally based off of this branch by this awesome contributor! 
https://github.com/buzzfeed/solid/pull/458
I tweaked the copy on this original PR and added the space-between/space-around styles for align-items (the original branch only had this for justify-content).
> Solid 421 flex between around

- _lib/solid-base/_typography.scss
Adds font-weight: normal (with no importants) to all header elements by default. Counteracts user agent stylesheet change which bolds header elements by default. Issue originally reported on the homepage.
Current: https://www.dropbox.com/s/tzi7bcx0y3329t7/Screenshot%202017-06-28%2010.34.12.png?dl=0
Expected: https://www.dropbox.com/s/mdb57aie1mqm15b/Screenshot%202017-06-28%2010.34.51.png?dl=0
> SOLID-438 reset header elements to normal font weights

- docs/mixins.html
On this page: solid.buzzfeed.com/mixins.html, the custom button class in the code snippet was missing a dash. We typically write modifier classes (like custom button classes that rely on the button class) with double dashes (button button--funtown), and the docs should reflect that.
> Added double-dash to the custom button class mixin

- _lib/solid-components/_messaging.scss
- docs/messaging.html
Context in this card: 
https://buzzfeed.atlassian.net/browse/SOLID-401
- Added: float left to the icon svgs, and added a margin-left on the message text
> Text Shouldn't Wrap Around Icon in the Page Message Components

- _lib/_solid-base.scss
- _lib/solid-base/_deprecated.scss
- _lib/solid-utilities/_flexbox.scss
- docs/flexbox.html
Added deprecated.scss file: for classes we feel should be deprecated before cold-removing them
Moved the deprecated page messaging styles to that file ☝️ 
Added the prefixed flex display class
Moved non-prefixed flex display class to the new fancy deprecated.scss file (kind of an oxymoron)
Added prefixed flex class to the documentation
> Added prefixed flex class & deprecated scss file

- _lib/solid-helpers/_variables.scss
- _lib/solid-utilities/_colors.scss
- package.json
- release-notes/2017-08-22-2.9.0.html
We have a few places in dashboard where we map platforms (of which BuzzFeed is one) to solid colors. As we do more with BuzzFeed O&O stats, we need a BuzzFeed solid color.
> add $fill-buzzfeed color

- _lib/solid-utilities/_buttons.scss
- package.json
- release-notes/2017-10-18-2.9.2.html
I'm proposing that we change the white button hover color to an opacity change instead of a darker white (aka gray) because it's super dull on dark backgrounds. And ultimately, you'd ALWAYS use this white button on a dark background. The opacity change on hover is more elegant than the gray.
Current white button hover state (fill darken): http://take.ms/wuQ9w
Proposed white button hover state (opacity change): http://take.ms/Y3Ody
> Adjust button white hover color

- package.json
In npm 5.3.0 it attempts to flatten all dependencies. grunt 0.4.5 and grunt-contrib-clean 1.1.0 have conflicting requirements and this cause a build error.
Thankfully updating to 1.0.1 required no application changes!
> Use the latest grunt version

- _lib/solid-components/_cards.scss
- package.json
- release-notes/2017-12-13-2.11.0.html
Having a mixin for the card styles will allow teams to safely reuse those styles without affecting the original `.card` class.
Before:
```sass
@import "solid-components/cards";
.custom-card {
@extend .card;
}
```
which compiles to
```css
.custom-card, .card {
border: 1px solid rgba(0,0,0,.1);
border-radius: 3px;
// ...
}
```
After:
```sass
@import "solid-components/cards";
.custom-card {
@include card();
}
```
which compiles to
```css
.card {
border: 1px solid rgba(0,0,0,.1);
border-radius: 3px;
// ...
}
.custom-card {
border: 1px solid rgba(0,0,0,.1);
border-radius: 3px;
// ...
}
```
> SITE-5296: solid: Make a mixin for the card styles

- _lib/solid-components/_popovers.scss
- package.json
- release-notes/2018-01-5-2.10.6.html
- release-notes/2018-01-9-2.10.6.html
top & bottom popover names are flipped by accident
intended behavior
> Popover Top/Bottom fix

- _lib/solid-utilities/_flexbox.scss
- _lib/solid-utilities/_layout.scss
- package.json
- release-notes/2018-02-21-2.10.7.html
The current ordering means that the `xs-flex` rule is impossible to override with other display modes at larger breakpoints with rules such as `sm-block` etc. Putting the display rule alongside the others should fix this quirk.
Bug: https://codepen.io/jackwreid/pen/qxXwvq
> Move flexbox display mode rule next to other display modes

- _lib/solid-helpers/_variables.scss
- _lib/solid-utilities/_forms.scss
- package.json
- release-notes/2019-03-09-2.11.1.html
This commit adds a blue outline to solid checkboxes when users use tabs to select the checkbox
> OOA11Y-259 make solid checkbox accessible
